# Generated by Django 2.2.5 on 2019-10-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizacao', models.CharField(max_length=150)),
                ('texto_apresentacao', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_valid', models.BooleanField(default=False)),
                ('apresentecao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Apresentacao')),
                ('organizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Realizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=150)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=150)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='MicroEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=300)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Programacao')),
            ],
        ),
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=150)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
    ]
