# Generated by Django 2.2.5 on 2020-02-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_auto_20200220_2010'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='tipo',
        ),
        migrations.AddField(
            model_name='dia',
            name='data',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizador.Organizador'),
        ),
    ]
