# Generated by Django 2.2.5 on 2020-01-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='img1',
            new_name='banner',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='img3',
        ),
        migrations.AddField(
            model_name='evento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(default='eoq', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='onde',
            field=models.CharField(default='eoq', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='quando',
            field=models.CharField(default='eoq', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='sobre',
            field=models.TextField(default='eoq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='telefone',
            field=models.CharField(default='eoq', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='apresentecao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Apresentacao'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Organizador'),
        ),
        migrations.AlterField(
            model_name='microevento',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Programacao'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='programacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='realizador',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento'),
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/palestrante')),
                ('resumo', models.CharField(max_length=200)),
                ('apresentacao', models.TextField()),
                ('microevento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.MicroEvento')),
            ],
        ),
    ]
