# Generated by Django 2.2.5 on 2020-02-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200220_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Dia'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
