# Generated by Django 2.2.5 on 2020-01-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200124_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='apresentecao',
        ),
    ]
