# Generated by Django 2.2.5 on 2020-02-28 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20200220_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento'),
        ),
    ]
