# Generated by Django 2.2.5 on 2020-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_apresentecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
