# Generated by Django 2.2.5 on 2020-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20200210_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='instagram',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
