# Generated by Django 2.2.5 on 2020-02-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_palestrante_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='apresentacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='resumo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
