# Generated by Django 2.2.5 on 2020-01-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20200124_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programacao',
            new_name='Dia',
        ),
        migrations.RenameField(
            model_name='microevento',
            old_name='programacao',
            new_name='dia',
        ),
    ]
