# Generated by Django 2.2.5 on 2020-01-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20200124_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apresentacao',
        ),
    ]
