# Generated by Django 2.2.5 on 2020-02-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20200227_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
