# Generated by Django 2.2.5 on 2020-02-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_delete_apresentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/banner'),
        ),
    ]
