# Generated by Django 2.2.5 on 2020-02-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20200229_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='foto',
            field=models.ImageField(blank=True, default='perfil/default.png', null=True, upload_to='perfil/palestrante'),
        ),
    ]
