# Generated by Django 2.2.5 on 2020-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200203_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microevento',
            name='local',
        ),
        migrations.AddField(
            model_name='microevento',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microevento',
            name='tipo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='onde',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quando',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='microevento',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
