# Generated by Django 2.2.5 on 2020-02-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200205_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicroEvento',
            new_name='Atividade',
        ),
        migrations.RenameField(
            model_name='palestrante',
            old_name='microevento',
            new_name='atividade',
        ),
    ]
