# Generated by Django 2.2.5 on 2020-02-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20200210_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='palestrante',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='realizador',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
