# Generated by Django 2.2.5 on 2020-03-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20200303_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
