# Generated by Django 2.2.5 on 2020-03-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20200303_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
