# Generated by Django 2.2.5 on 2020-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20200305_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='apoiadores/banner'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='patrocinadores/banner'),
        ),
        migrations.AlterField(
            model_name='realizador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='realizadores/banner'),
        ),
    ]
