# Generated by Django 3.0.6 on 2020-06-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20200309_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiador',
            name='foto',
            field=models.ImageField(upload_to='apoiadores/banner'),
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='foto',
            field=models.ImageField(upload_to='patrocinadores/banner'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='realizador',
            name='foto',
            field=models.ImageField(upload_to='realizadores/banner'),
        ),
        migrations.AlterField(
            model_name='realizador',
            name='link',
            field=models.CharField(max_length=150),
        ),
    ]
