# Generated by Django 3.0.6 on 2020-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20200627_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
