# Generated by Django 2.2.5 on 2020-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200109_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='nome',
        ),
        migrations.AddField(
            model_name='organizador',
            name='first_name',
            field=models.CharField(default='pedro', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organizador',
            name='last_name',
            field=models.CharField(default='marques', max_length=80),
            preserve_default=False,
        ),
    ]
