# Generated by Django 2.2.5 on 2020-01-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200109_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
