# Generated by Django 2.2.5 on 2020-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizador_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
