# Generated by Django 2.2.5 on 2020-01-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200120_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/administrador'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/organizador'),
        ),
    ]
