# Generated by Django 3.0.4 on 2020-04-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_auto_20200220_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='foto',
        ),
    ]
