# Generated by Django 3.0.6 on 2020-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0004_organizador_has_changed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
