# Generated by Django 3.0.6 on 2020-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0005_auto_20200619_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='full_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
